# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS

  # ====== กำหนดชื่อผู้ใช้และรหัสผ่าน ======
  USERNAME = "panuwat"
  PASSWORD = "panuwat"

  # ==========================================
  # VM 2: App Tier (Node.js)
  # IP: 192.168.56.111
  # ==========================================
  config.vm.define "app" do |app|
    app.vm.hostname = "app-server"
    app.vm.network "private_network", ip: "192.168.56.111"

    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "VM2-NodeJS-App"
    end

    app.vm.provision "shell", inline: <<-SHELL
      sudo useradd -m -s /bin/bash #{USERNAME}
      echo "#{USERNAME}:#{PASSWORD}" | sudo chpasswd
      sudo usermod -aG sudo #{USERNAME}
    SHELL
  end

  # ==========================================
  # VM 3: Database Tier (PostgreSQL)
  # IP: 192.168.56.112
  # ==========================================
  config.vm.define "db" do |db|
    db.vm.hostname = "db-server"
    db.vm.network "private_network", ip: "192.168.56.112"

    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "VM3-Postgres-DB"
    end

    db.vm.provision "shell", inline: <<-SHELL
      sudo useradd -m -s /bin/bash #{USERNAME}
      echo "#{USERNAME}:#{PASSWORD}" | sudo chpasswd
      sudo usermod -aG sudo #{USERNAME}
    SHELL
  end
end
